name: Package Application with Pyinstaller

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Windows Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: audiometer

    - uses: actions/upload-artifact@v2
      with:
        name: audiometer
        path: dist/windows
