name: Package Application with Pyinstaller

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Package Windows Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          spec: audiometer.spec
          path: .

      - name: Publish Windows Application
        uses: actions/upload-artifact@v2
        with:
          name: audiometer
          path: audiometer/dist/windows
