name: Test

on: 
  pull_request: {}
  push:
    branches: main
    tags: "*"

env:
  COVERAGE_SKIP: nocover-ci

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.5

      - name: Install dependencies with pipenv
        run: |
          pip install pipenv
          sudo apt-get install -y portaudio19-dev tk
          pipenv install --verbose --deploy --dev

      - run: pipenv run isort --recursive --diff .
      - run: pipenv run black --check .
      - run: pipenv run flake8
      - run: pipenv run mypy
      - run: pipenv run pytest --cov --cov-fail-under=100

  docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build . -t audiometer:test

# Do not smoke test the GUI within Docker. Commenting out until a web interface is developed.
#      - name: Smoke test docker image
#        run: |
#          docker run --rm audiometer:test 10
